#bus_driving_server_payara

###
@urlbase =http://localhost:8085/Bus_driving_server_payara-1.0-SNAPSHOT/api
# @name loginAdmin
POST {{urlbase}}/login
Content-Type: application/json

{
  "username": {{adminUsername}},
  "password": {{adminPassword}}
}
