#bus_driving_server_payara

#please remember to change the activation_date before testing

###
@urlbase =http://localhost:8085/Bus_driving_server_payara-1.0-SNAPSHOT/api

###
# @name activateUnactivatedAccount
GET {{urlbase}}/activate?email=tosigether598@gmail.com&code=5s8TqlVUwWhJ298mbJGRFVOUTzaSDqf08UVIVOd06Iw%3D

