#bus_driving_server_payara


###
# @name loginActivatedDriver
POST {{urlBase}}/login
Content-Type: application/json

{
  "username": "{{activatedDriverUsername}}",
  "password": "{{activatedDriverPassword}}"
}

###
# @name getAllLines
GET {{urlBase}}/lines


