#bus_driving_server_spring_with_tokens

###
# @name loginActivatedDriver
POST {{urlBase}}auth/login
Content-Type: application/json

{
  "username": "{{activatedDriverUsername}}",
  "password": "{{activatedDriverPassword}}"
}
> {%
    client.global.set("access_token", response.body.tokenPair.accessToken);
    client.global.set("refresh_token", response.body.tokenPair.refreshToken);
%}

###
# @name refreshToken
POST {{urlBase}}auth/refresh
Content-Type: application/json

{
  "token": "{{refresh_token}}"
}

> {%
    client.global.set("new_access_token", response.body.accessToken);
    client.global.set("new_refresh_token", response.body.refreshToken);
%}

###
# @name getAllStops
GET {{urlBase}}/stops
Authorization: Bearer {{new_access_token}}

