#bus_driving_server_payara_with_tokens

###
# @name loginAdmin
POST {{urlBase}}/login
Content-Type: application/json

{
  "username": "{{adminUsername}}",
  "password": "{{adminPassword}}"
}
> {%
    client.global.set("access_token", response.headers.get("Authorization"));
    client.global.set("refresh_token", response.headers.get("Refresh"));
%}

###
# @name getDriverIdByUsername
GET {{urlBase}}/drivers/username/{{driverUsername}}
Authorization: {{access_token}}

