#bus_driving_server_payara

###
# @name register
POST {{urlBase}}/register
Content-Type: application/json

{
  "firstName": "Marcos",
  "lastName": "Vazquez",
  "phone": "623382826",
  "username": "marcos",
  "password": "passwordVazquez22",
  "email": "mcclaraboo@gmail.com"
}
