#bus_driving_server_spring_with_tokens

###
# @name loginActivatedDriver
POST {{urlBase}}auth/login
Content-Type: application/json

{
  "username": "{{activatedDriverUsername}}",
  "password": "{{activatedDriverPassword}}"
}
> {%
    client.global.set("access_token", response.body.tokenPair.accessToken);
    client.global.set("refresh_token", response.body.tokenPair.refreshToken);
%}

###
# @name getAllStops
GET {{urlBase}}/stops
Authorization: Bearer {{access_token}}


