#bus_driving_server_payara_with_tokens

###
# @name loginActivatedDriver
POST {{urlBase}}/login
Content-Type: application/json

{
  "username": "{{activatedDriverUsername}}",
  "password": "{{activatedDriverPassword}}"
}
> {%
    client.global.set("access_token", response.headers.valueOf("Authorization"));
    client.global.set("refresh_token", response.headers.valueOf("Refresh"));
%}

###
# @name getLine
GET {{urlBase}}/lines/100
Authorization: {{access_token}}

