#bus_driving_server_payara_with_tokens

###
# @name register
POST {{urlBase}}/register
Content-Type: application/json

{
  "firstName": "Elena",
  "lastName": "Delgado",
  "phone": "627389512",
  "username": "u1",
  "password": "p1",
  "email": "eDelgado99@gmail.com"
}
