#bus_driving_server_spring_with_tokens

###
# @name register
POST {{urlBase}}register
Content-Type: application/json

{
  "firstName": "Sara",
  "lastName": "Jimenez",
  "phone": "632338256",
  "username": "bbbb",
  "password": "1234",
  "email": "tosigether598@gmail.com"
}
