#bus_driving_server_payara

###
@urlbase =http://localhost:8085/Bus_driving_server_payara-1.0-SNAPSHOT/api
# @name loginAdmin
POST {{urlbase}}/login
Content-Type: application/json

{
  "username": {{adminUsername}},
  "password": {{adminPassword}}
}


###
# @name loginActivatedDriver
POST {{urlbase}}/login
Content-Type: application/json

{
  "username": {{activatedDriverUsername}},
  "password": {{activatedDriverPassword}}
}

###
# @name loginUnactivatedDriver
POST {{urlbase}}/login
Content-Type: application/json

{
  "username": {{unactivatedDriverUsername}},
  "password": {{unactivatedDriverPassword}}
}

###
# @name register
GET {{urlbase}}/register
Content-Type: application/json

{
  "firstName": "Celia4",
  "lastName": "Solera4",
  "phone": "623282914",
  "username": "u10",
  "password": "p10",
  "email": "mcclaraboo@gmail.com"
}

###
# @name activateUnactivatedAccount
PUT {{urlbase}}/activate?email={{unactivatedAccountEmail}}&code={{unactivatedAccountCode}}

###
# @name resendActivationCode
PUT {{urlbase}}/resend-code?email={{resendCodeEmail}}}

###
# @name activateActivatedAccount
PUT {{urlbase}}/activate?email={{activatedAccountEmail}}&code={{activatedAccountCode}}

###
# @name getDrivers
GET {{urlbase}}/drivers

###
# @name getDriver
GET {{urlbase}}/drivers/1

###
# @name getAllStops
GET {{urlbase}}/stops

###
# @name getAllStopsInALine
GET {{urlbase}}/stops/line/100

###
# @name getAllLines
GET {{urlbase}}/lines

###
# @name getLine
GET {{urlbase}}/lines/100

###
# @name getLinesInAStop
GET {{urlbase}}/lines/stop/4757

